name: Sync to Upstream

on:
  schedule:
    - cron: '*/5 * * * *'
    # scheduled at 07:12 every Monday and Thursday
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout HEAD
      uses: actions/checkout@v2
      with:
        ref: master
        
    
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: git config pull.rebase false

    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
    - name: Pull upstream changes
      id: sync
      uses: wp-experiments//Fork-Sync-With-Upstream-action@v1
      with:
        upstream_repository: shreyapohekar/hello-world
        upstream_branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
